// Mock data for featured projects and founders
export const mockProjects = [
  {
    id: 'mock-1',
    name: 'Solana DeFi Protocol',
    description: 'Next-generation decentralized exchange with lightning-fast swaps and zero gas fees. Building the future of DeFi on Solana.',
    tagline: 'Revolutionary DEX on Solana',
    logoUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiBmaWxsPSIjMTQxNDFGIi8+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9ImdyYWQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPgo8c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojOUE0NUZGIi8+CjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6IzEzRTJDMiIvPgo8L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+Cjxwb2x5Z29uIHBvaW50cz0iNTAsODAgMTUwLDgwIDEzMCw2MCAxNzAsNjAgMTUwLDQwIDUwLDQwIiBmaWxsPSJ1cmwoI2dyYWQpIi8+Cjxwb2x5Z29uIHBvaW50cz0iNTAsMTIwIDE1MCwxMjAgMTMwLDEwMCAxNzAsMTAwIDE1MCw4MCA1MCw4MCIgZmlsbD0idXJsKCNncmFkKSIvPgo8cG9seWdvbiBwb2ludHM9IjUwLDE2MCAxNTAsMTYwIDEzMCwxNDAgMTcwLDE0MCAxNTAsMTIwIDUwLDEyMCIgZmlsbD0idXJsKCNncmFkKSIvPgo8L3N2Zz4=',
    projectUrl: 'https://solana.com',
    techStack: ['Solana', 'Rust', 'Anchor', 'TypeScript'],
    founder: {
      name: 'Anatoly Yakovenko',
      username: 'aeyakovenko',
      bio: 'Co-Founder of Solana Labs',
      profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI9z0sJ3VIMfMPWmGwoiue50pbWnUsBppjeg&s',
      socialLink: 'https://twitter.com/aeyakovenko',
      wallet: '11111111111111111111111111111111',
      projects: 3,
    },
    status: 'closed',
  },
  {
    id: 'mock-2',
    name: 'Phantom Wallet',
    description: 'The most popular crypto wallet on Solana. Trusted by millions to securely store, send, swap, and stake tokens and NFTs.',
    tagline: 'Your gateway to Solana',
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUFcEVOGADpYWBSKJnwYGZdzbgjToASHQnk0-lg9brWXdl2H3pwzDRBwCazIhbowOT5Mg&usqp=CAU',
    projectUrl: 'https://phantom.app',
    techStack: ['Solana', 'React', 'TypeScript', 'Web3.js'],
    founder: {
      name: 'Brandon Millman',
      username: 'millerman',
      bio: 'Co-Founder & CEO of Phantom Wallet',
      profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI7exBU1L3v2uWY-zsw5FAnsipQM-hzKyymQ&s',
      socialLink: 'https://twitter.com/millerman',
      wallet: '22222222222222222222222222222222',
      projects: 1,
    },
    status: 'closed',
  },
  {
    id: 'mock-3',
    name: 'Magic Eden',
    description: 'The leading NFT marketplace on Solana. Trade, mint, and discover unique digital assets with lightning speed.',
    tagline: 'Leading Solana NFT Marketplace',
    logoUrl: 'https://file.coinexstatic.com/2024-08-20/0D36869F670E168996ECFFBBE66BC7F2.png',
    projectUrl: 'https://magiceden.io',
    techStack: ['Solana', 'Anchor', 'React', 'TypeScript'],
    founder: {
      name: 'Jack Lu',
      username: 'jack_lu_',
      bio: 'Co-Founder & CEO of Magic Eden',
      profilePicture: 'https://i.insider.com/62abb41f1c7744001959c8d8?width=700',
      socialLink: 'https://twitter.com/jack_lu_',
      wallet: '33333333333333333333333333333333',
      projects: 1,
    },
    status: 'closed',
  },
  {
    id: 'mock-4',
    name: 'DAO Governance Tool',
    description: 'Streamlined governance platform for DAOs. Vote, propose, and execute decisions on-chain with full transparency.',
    tagline: 'Power to the community',
    logoUrl: 'https://avatars.githubusercontent.com/u/73580507?s=200&v=4', // Realms
    projectUrl: 'https://realms.today',
    techStack: ['Solana', 'Rust', 'TypeScript', 'PostgreSQL'],
    founder: {
      name: 'Naval Ravikant',
      username: 'naval',
      bio: 'AngelList Founder, Crypto Investor',
      profilePicture: 'https://pbs.twimg.com/profile_images/1417825967562461184/H6uLvpzU_400x400.jpg',
      socialLink: 'https://twitter.com/naval',
      wallet: '44444444444444444444444444444444',
      projects: 2,
    },
    status: 'closed',
  },
  {
    id: 'mock-5',
    name: 'Solana Mobile Wallet',
    description: 'Secure, fast, and beautiful mobile wallet for Solana. Manage tokens, NFTs, and dApps from your phone.',
    tagline: 'Your keys, your crypto',
    logoUrl: 'https://avatars.githubusercontent.com/u/103535015?s=200&v=4', // Phantom
    projectUrl: 'https://phantom.app',
    techStack: ['Solana', 'React Native', 'TypeScript'],
    founder: {
      name: 'Brandon Millman',
      username: 'bmillman',
      bio: 'Phantom Wallet Co-Founder',
      profilePicture: 'https://pbs.twimg.com/profile_images/1595147842698383360/eNmV-HFb_400x400.jpg',
      socialLink: 'https://twitter.com/millerman',
      wallet: '55555555555555555555555555555555',
      projects: 1,
    },
    status: 'closed',
  },
  {
    id: 'mock-6',
    name: 'Liquid Staking Protocol',
    description: 'Stake your SOL and receive liquid staking tokens. Earn staking rewards while keeping your assets liquid for DeFi.',
    tagline: 'Stake without locking',
    logoUrl: 'https://avatars.githubusercontent.com/u/90631007?s=200&v=4', // Marinade
    projectUrl: 'https://marinade.finance',
    techStack: ['Solana', 'Anchor', 'Rust', 'React'],
    founder: {
      name: 'Balaji Srinivasan',
      username: 'balajis',
      bio: 'Former CTO Coinbase, Angel Investor',
      profilePicture: 'https://pbs.twimg.com/profile_images/1535743685211725824/8QJl3ow__400x400.jpg',
      socialLink: 'https://twitter.com/balajis',
      wallet: '66666666666666666666666666666666',
      projects: 3,
    },
    status: 'closed',
  },
];

export const mockFounders = mockProjects.map(p => p.founder);
